name: Publish via CI

on:
  push:
    tags: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
  publish:
    runs-on: ubuntu-latest
    needs: build
    env:
      GHTOKEN: ${{ secrets.GHTOKEN }}
      GHACTOR: ${{ secrets.GHACTOR }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish full library and standalone library
      run: ./gradlew publishAllPublicationsToGitHubPackagesRepository